# Generated by Django 3.0.8 on 2020-10-23 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_boardtest_file_notice'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='boardtest',
            table='boardTest',
        ),
    ]
