# Generated by Django 3.0.8 on 2020-10-23 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_auto_20201023_1515'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoardTest',
            new_name='BoardTest1',
        ),
        migrations.AlterModelTable(
            name='boardtest1',
            table='board_test1',
        ),
    ]
