# Generated by Django 3.1.5 on 2021-01-27 07:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20201023_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('content', models.TextField(default=False)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
