# Generated by Django 3.1.5 on 2021-01-27 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_dog1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog1',
            options={'managed': True},
        ),
    ]
