# Generated by Django 3.1.5 on 2021-01-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_auto_20210127_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data', models.JSONField()),
                ('content', models.TextField(default=False)),
            ],
            options={
                'db_table': 'Dog',
            },
        ),
    ]
