# Generated by Django 3.1.5 on 2021-01-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_dog2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog2',
            name='content',
            field=models.TextField(default=False, null=True),
        ),
    ]
