# Generated by Django 3.1.5 on 2021-01-28 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0010_auto_20210127_1806'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dog2',
            table='dog_json',
        ),
    ]
